### ISSUE TITLE
Comentários Default IDE

### ISSUE THREAD

**Issue by osmarbraz** [lucasrengel/A3-Programacao-e-Solucoes-Computacionais#7]
Limpe comentários default da IDE das classes

/*

Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
*/

**Comment by lucasrengel** [comment]
comentarios default deletado

**Comment by osmarbraz** [comment]
Não foi resolvido!
